name: Sync fork

on:
  schedule:
    - cron: '5 19 * * *'  # 19:05 UTC time (4:05 a.m. Korean time)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Sync with upstream
      run: |
        gh api --method POST \
          "repos/${GITHUB_REPOSITORY}/merge-upstream" \
          -f branch="${{ github.event.repository.default_branch }}"
      env:
        GH_TOKEN: ${{ github.token }}
